In [1]:
import torch
import numpy as np

**Initializing a Tensor**

In [2]:
data=[[1,2],[3,4]]
x_data=torch.tensor(data)

In [3]:
np_array=np.array(data)
x_np=torch.from_numpy(np_array)

In [4]:
x_ones=torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand=torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.4188, 0.3995],
        [0.2740, 0.7074]]) 



In [9]:
shape=(2,3,)
rand_tensor=torch.rand(shape)
rand_tensor

tensor([[0.7851, 0.3047, 0.9489],
        [0.1144, 0.0595, 0.0406]])

In [10]:
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.7851, 0.3047, 0.9489],
        [0.1144, 0.0595, 0.0406]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [11]:
tensor=torch.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device of tensor: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


In [14]:
if torch.backends.mps.is_available():
    tensor=tensor.to("mps")

In [15]:
tensor.device

device(type='mps', index=0)

In [20]:
tensor=torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:,0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1]=0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [21]:
tensor[2,...]

tensor([1., 0., 1., 1.])

In [22]:
t1=torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [24]:
t1=torch.cat([tensor,tensor,tensor],dim=0)
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [28]:
k=torch.stack((tensor,tensor,tensor))
k.size()

torch.Size([3, 4, 4])

In [29]:
y1=tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [30]:
y2=tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [38]:
y3=torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3) #it multiplies tensor and tensor.transpose and assigns it y3

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [35]:
torch.matmul(tensor, y3.T)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
z1=tensor*tensor
z2=tensor.mul(tensor) #does elementwise multiplication

In [41]:
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [42]:
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [43]:
z3=torch.rand_like(tensor)
torch.mul(tensor,tensor,out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [44]:
agg=tensor.sum()
agg

tensor(12.)

In [45]:
agg_item=agg.item()
agg_item

12.0

In [46]:
print(agg_item, type(agg_item))

12.0 <class 'float'>


In [47]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [56]:
t=torch.ones(5)
print(f"t: {t}")

t: tensor([1., 1., 1., 1., 1.])


In [57]:
n=t.numpy()
print(f"n: {n}")

n: [1. 1. 1. 1. 1.]


In [58]:
if torch.backends.mps.is_available():
    t=t.to("mps")

In [59]:
t.add_(1)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], device='mps:0')
[1. 1. 1. 1. 1.]


In [60]:
n=np.ones(5)
t=torch.from_numpy(n)

In [61]:
np.add(n,1,out=n)
print(t)
print(n)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
