In [3]:
import torch
import numpy as np

data = [[1,2,5], [3,4,6]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2, 5],
        [3, 4, 6]])

In [4]:
x_data.shape

torch.Size([2, 3])

In [5]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2, 5],
        [3, 4, 6]], dtype=torch.int32)

In [6]:
x_ones = torch.ones_like(x_data)
print(f"ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"randomr tensor: \n {x_rand} \n")

ones tensor: 
 tensor([[1, 1, 1],
        [1, 1, 1]]) 

randomr tensor: 
 tensor([[0.2731, 0.1545, 0.4621],
        [0.1915, 0.6948, 0.6158]]) 



In [9]:
my_shape = (2,3,)
rand_tensor = torch.rand(my_shape)
ones_tensor = torch.ones(my_shape)
zeros_tensor = torch.zeros(my_shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0505, 0.9568, 0.9299],
        [0.6342, 0.3551, 0.5474]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [14]:
tensor = torch.rand(4, 4).to(device)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([0.5439, 0.7556, 0.9668, 0.5209], device='cuda:0')
First column: tensor([0.5439, 0.0232, 0.0033, 0.0955], device='cuda:0')
Last column: tensor([0.5209, 0.0136, 0.4169, 0.1093], device='cuda:0')
tensor([[0.5439, 0.0000, 0.9668, 0.5209],
        [0.0232, 0.0000, 0.2430, 0.0136],
        [0.0033, 0.0000, 0.1213, 0.4169],
        [0.0955, 0.0000, 0.4991, 0.1093]], device='cuda:0')


In [17]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[0.5439, 0.0000, 0.9668, 0.5209, 0.5439, 0.0000, 0.9668, 0.5209, 0.5439,
         0.0000, 0.9668, 0.5209],
        [0.0232, 0.0000, 0.2430, 0.0136, 0.0232, 0.0000, 0.2430, 0.0136, 0.0232,
         0.0000, 0.2430, 0.0136],
        [0.0033, 0.0000, 0.1213, 0.4169, 0.0033, 0.0000, 0.1213, 0.4169, 0.0033,
         0.0000, 0.1213, 0.4169],
        [0.0955, 0.0000, 0.4991, 0.1093, 0.0955, 0.0000, 0.4991, 0.1093, 0.0955,
         0.0000, 0.4991, 0.1093]], device='cuda:0')

In [20]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

tensor([[1.5019, 0.2547, 0.3362, 0.5914],
        [0.2547, 0.0598, 0.0352, 0.1250],
        [0.3362, 0.0352, 0.1885, 0.1064],
        [0.5914, 0.1250, 0.1064, 0.2702]], device='cuda:0')
tensor([[1.5019, 0.2547, 0.3362, 0.5914],
        [0.2547, 0.0598, 0.0352, 0.1250],
        [0.3362, 0.0352, 0.1885, 0.1064],
        [0.5914, 0.1250, 0.1064, 0.2702]], device='cuda:0')


In [22]:
y3 = torch.rand_like(y1)
print(y3)
print(torch.matmul(tensor, tensor.T, out=y3))

tensor([[0.8064, 0.7520, 0.6185, 0.0942],
        [0.2911, 0.2216, 0.2987, 0.7420],
        [0.3131, 0.7990, 0.9806, 0.9468],
        [0.5612, 0.6335, 0.0553, 0.6732]], device='cuda:0')
tensor([[1.5019, 0.2547, 0.3362, 0.5914],
        [0.2547, 0.0598, 0.0352, 0.1250],
        [0.3362, 0.0352, 0.1885, 0.1064],
        [0.5914, 0.1250, 0.1064, 0.2702]], device='cuda:0')


In [23]:
y3

tensor([[1.5019, 0.2547, 0.3362, 0.5914],
        [0.2547, 0.0598, 0.0352, 0.1250],
        [0.3362, 0.0352, 0.1885, 0.1064],
        [0.5914, 0.1250, 0.1064, 0.2702]], device='cuda:0')

In [25]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

print(z1)
print(z2)

z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[2.9587e-01, 0.0000e+00, 9.3472e-01, 2.7129e-01],
        [5.3838e-04, 0.0000e+00, 5.9051e-02, 1.8556e-04],
        [1.1143e-05, 0.0000e+00, 1.4704e-02, 1.7381e-01],
        [9.1251e-03, 0.0000e+00, 2.4913e-01, 1.1946e-02]], device='cuda:0')
tensor([[2.9587e-01, 0.0000e+00, 9.3472e-01, 2.7129e-01],
        [5.3838e-04, 0.0000e+00, 5.9051e-02, 1.8556e-04],
        [1.1143e-05, 0.0000e+00, 1.4704e-02, 1.7381e-01],
        [9.1251e-03, 0.0000e+00, 2.4913e-01, 1.1946e-02]], device='cuda:0')
tensor([[0.5100, 0.9427, 0.7565, 0.2797],
        [0.5457, 0.2293, 0.9745, 0.6185],
        [0.4140, 0.1174, 0.0819, 0.9948],
        [0.0029, 0.7912, 0.2617, 0.0378]], device='cuda:0')
tensor([[2.9587e-01, 0.0000e+00, 9.3472e-01, 2.7129e-01],
        [5.3838e-04, 0.0000e+00, 5.9051e-02, 1.8556e-04],
        [1.1143e-05, 0.0000e+00, 1.4704e-02, 1.7381e-01],
        [9.1251e-03, 0.0000e+00, 2.4913e-01, 1.1946e-02]], device='cuda:0')


In [26]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

3.55688738822937 <class 'float'>


In [27]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[0.5439, 0.0000, 0.9668, 0.5209],
        [0.0232, 0.0000, 0.2430, 0.0136],
        [0.0033, 0.0000, 0.1213, 0.4169],
        [0.0955, 0.0000, 0.4991, 0.1093]], device='cuda:0') 

tensor([[5.5439, 5.0000, 5.9668, 5.5209],
        [5.0232, 5.0000, 5.2430, 5.0136],
        [5.0033, 5.0000, 5.1213, 5.4169],
        [5.0955, 5.0000, 5.4991, 5.1093]], device='cuda:0')


In [28]:
t = torch.ones(5)
print(f"f: {t}")
n = t.numpy()
print(f"n: {n}")

f: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [29]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [30]:
t.to(device)
t

tensor([2., 2., 2., 2., 2.])

In [35]:
tensor.add_(2)
tensor

tensor([[7.5439, 7.0000, 7.9668, 7.5209],
        [7.0232, 7.0000, 7.2430, 7.0136],
        [7.0033, 7.0000, 7.1213, 7.4169],
        [7.0955, 7.0000, 7.4991, 7.1093]], device='cuda:0')

In [34]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

array([4., 4., 4., 4., 4.], dtype=float32)

In [39]:
x_np = x_np.to(device)
x_np

tensor([[1, 2, 5],
        [3, 4, 6]], device='cuda:0', dtype=torch.int32)

In [40]:
x_np.add_(5)
print(x_np)
print(np_array)

tensor([[ 6,  7, 10],
        [ 8,  9, 11]], device='cuda:0', dtype=torch.int32)
[[1 2 5]
 [3 4 6]]
